apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Домашнее задание по Нетологии</title> 
    </head>
    <body>
      <h1>Знание - сила!</h1>
      <p>Эта страница подключена через ConfigMap</p>
    </body>
    </html>